learning_rate: 3.0e-4
n_steps: 2048
batch_size: 256
gamma: 1.0
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
n_epochs: 10
target_kl: 0.03
save_freq: 50000
total_timesteps: 5000000